name: Update data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Data
        uses: ./.github/actions/update-data
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if [[ $(git status --porcelain) ]]; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT

      - name: Build changes
        if: steps.git-check.outputs.modified == 'true'
        run: npm run build

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'vuzaldo'
          git config --global user.email '121903720+vuzaldo@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto-update of Spellstone Data - $(date +%Y-%m-%d)"
          git push
